export const autos = [
  {
    id: 1,
    marca: "Toyota",
    modelo: "Corolla",
    segmento: "Sedán",
    precio: 23000,
    foto: "../../imagenes/toyota1.jpeg",
  },
  {
    id: 2,
    marca: "Ford",
    modelo: "Escape",
    segmento: "SUV",
    precio: 31000,
    foto: "/imagenes/ford1.jpeg",
  },
  {
    id: 3,
    marca: "Chevrolet",
    modelo: "Onix",
    segmento: "Hatchback",
    precio: 18000,
    foto: "/imagenes/chevrolet1.jpeg",
  },
  {
    id: 4,
    marca: "Volkswagen",
    modelo: "Tiguan",
    segmento: "SUV",
    precio: 34000,
    foto: "/imagenes/volkswagen1.jpeg",
  },
  {
    id: 5,
    marca: "Honda",
    modelo: "Civic",
    segmento: "Sedán",
    precio: 25000,
    foto: "/imagenes/honda1.jpeg",
  },
  {
    id: 6,
    marca: "Peugeot",
    modelo: "208",
    segmento: "Hatchback",
    precio: 20000,
    foto: "/imagenes/peugeot1.jpeg",
  },
  {
    id: 7,
    marca: "Renault",
    modelo: "Duster",
    segmento: "SUV",
    precio: 22000,
    foto: "/imagenes/renault1.jpeg",
  },
  {
    id: 8,
    marca: "Nissan",
    modelo: "Sentra",
    segmento: "Sedán",
    precio: 24000,
    foto: "/imagenes/nissan1.jpeg",
  },
  {
    id: 9,
    marca: "Hyundai",
    modelo: "i20",
    segmento: "Hatchback",
    precio: 19500,
    foto: "/imagenes/hyundai1.jpeg",
  },
  {
    id: 10,
    marca: "Kia",
    modelo: "Sportage",
    segmento: "SUV",
    precio: 32000,
    foto: "/imagenes/kia1.jpeg",
  },
  {
    id: 11,
    marca: "Fiat",
    modelo: "Cronos",
    segmento: "Sedán",
    precio: 18500,
    foto: "/imagenes/fiat1.jpeg",
  },
  {
    id: 12,
    marca: "BMW",
    modelo: "Serie 3",
    segmento: "Sedán",
    precio: 45000,
    foto: "/imagenes/bmw1.jpeg",
  },
  {
    id: 13,
    marca: "Mercedes-Benz",
    modelo: "GLA",
    segmento: "SUV",
    precio: 48000,
    foto: "/imagenes/mercedes1.jpeg",
  },
  {
    id: 14,
    marca: "Jeep",
    modelo: "Renegade",
    segmento: "SUV",
    precio: 29000,
    foto: "/imagenes/jeep1.jpeg",
  },
  {
    id: 15,
    marca: "Mazda",
    modelo: "3",
    segmento: "Sedán",
    precio: 26000,
    foto: "/imagenes/mazda1.jpeg",
  },
  {
    id: 16,
    marca: "Mercedes-Benz",
    modelo: "Clase E",
    segmento: "Sedán",
    precio: 60000,
    foto: "/imagenes/mercedes2.jpeg",
  },
  {
    id: 17,
    marca: "Audi",
    modelo: "Q5",
    segmento: "SUV",
    precio: 55000,
    foto: "/imagenes/audi2.jpg",
  },
  {
    id: 18,
    marca: "BMW",
    modelo: "X5",
    segmento: "SUV",
    precio: 70000,
    foto: "/imagenes/bmw2.jpg",
  },
  {
    id: 19,
    marca: "Rolls-Royce",
    modelo: "Ghost",
    segmento: "Sedán de lujo",
    precio: 340000,
    foto: "/imagenes/ROLLS1.jpeg",
  },
  {
    id: 20,
    marca: "Ford",
    modelo: "Mustang",
    segmento: "Sedán de lujo",
    precio: 50.0,
    foto: "/imagenes/mustang3.jpg",
  },
];
