const clientes = [
  {
    id: 1,
    nombre: "Lucas",
    opinion: "Excelente atención y entrega rápida. Muy satisfecho.",
    valoracion: 5,
    fecha: "2024-11-10",
    imagen: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 2,
    nombre: "Camila",
    opinion: "Me asesoraron muy bien. Todo fue claro y ágil.",
    valoracion: 4,
    fecha: "2024-12-01",
    imagen: "https://randomuser.me/api/portraits/women/21.jpg",
  },
  {
    id: 3,
    nombre: "Diego",
    opinion: "Muy buena experiencia, volvería a comprar sin dudar.",
    valoracion: 5,
    fecha: "2025-01-15",
    imagen: "https://randomuser.me/api/portraits/men/31.jpg",
  },
  {
    id: 4,
    nombre: "Martina",
    opinion: "El auto llegó en tiempo y forma, sin sorpresas.",
    valoracion: 4,
    fecha: "2024-10-20",
    imagen: "https://randomuser.me/api/portraits/women/41.jpg",
  },
  {
    id: 5,
    nombre: "Julián",
    opinion: "Todo perfecto, me ayudaron con cada paso del proceso.",
    valoracion: 5,
    fecha: "2025-03-08",
    imagen: "https://randomuser.me/api/portraits/men/51.jpg",
  },
  {
    id: 6,
    nombre: "Florencia",
    opinion: "Servicio muy amable y cumplidores con lo prometido.",
    valoracion: 4,
    fecha: "2024-09-30",
    imagen: "https://randomuser.me/api/portraits/women/61.jpg",
  },
  {
    id: 7,
    nombre: "Tomás",
    opinion: "Compré mi primer auto con ellos y fue genial.",
    valoracion: 5,
    fecha: "2025-02-22",
    imagen: "https://randomuser.me/api/portraits/men/71.jpg",
  },
  {
    id: 8,
    nombre: "Valeria",
    opinion: "Me ofrecieron buenas opciones y me acompañaron en todo.",
    valoracion: 4,
    fecha: "2024-12-18",
    imagen: "https://randomuser.me/api/portraits/women/81.jpg",
  },
  {
    id: 9,
    nombre: "Nahuel",
    opinion: "Atención impecable. Todo fue más fácil de lo esperado.",
    valoracion: 5,
    fecha: "2025-01-05",
    imagen: "https://randomuser.me/api/portraits/men/91.jpg",
  },
  {
    id: 10,
    nombre: "Rocío",
    opinion: "Una experiencia simple, confiable y muy profesional.",
    valoracion: 5,
    fecha: "2025-03-26",
    imagen: "https://randomuser.me/api/portraits/women/99.jpg",
  },
];

export default clientes;
